### ISSUE TITLE
How to search..

### ISSUE THREAD

**Issue by systems-rebooter** [sashasimkin/vk_music#2]
How to search for 'Bla' song and download it after in HQ?

**Comment by sashasimkin** [comment]
Nohow. The search isn't implemented in this repo.

**Comment by shdown** [comment]
> How to search for 'Bla' song

`./vksearch Bla`, but you need to update the access_token, see my comment in the another issue.

> and download it after in HQ?

AFAIK vk does not report song’s “quality”.

> Nohow. The search isn't implemented in this repo.

What.

**Comment by sashasimkin** [comment]
Lol. Guys, are you confused the repo? :D There is no ability to search songs through **vk_music**, you're currently in.

**Comment by shdown** [comment]
Oh, sorry, I thought it’s snoopcatt/vksearch.

**Comment by sashasimkin** [comment]
Haha, I've found it.
Без проблем :)

**Comment by systems-rebooter** [comment]
:) Thanks both of u
